export const SEARCH_QUERIES = [
  "carrot",
  "broccoli",
  "asparagus",
  "cauliflower",
  "corn",
  "cucumber",
  "green pepper",
  "lettuce",
  "mushrooms",
  "onion",
  "potato",
  "pumpkin",
  "red pepper",
  "tomato",
  "beetroot",
  "brussel sprouts",
  "peas",
  "zucchini",
  "radish",
  "sweet potato",
  "artichoke",
  "leek",
  "cabbage",
  "celery",
  "chili",
  "garlic",
  "basil",
  "coriander",
  "parsley",
  "dill",
  "rosemary",
  "oregano",
  "cinnamon",
  "saffron",
  "green bean",
  "bean",
  "chickpea",
  "lentil",
  "apple",
  "apricot",
  "avocado",
  "banana",
  "blackberry",
  "blackcurrant",
  "blueberry",
  "boysenberry",
  "cherry",
  "coconut",
  "fig",
  "grape",
  "grapefruit",
  "kiwi",
  "lemon",
  "lime",
  "lychee",
  "mandarin",
  "mango",
  "melon",
  "nectarine",
  "orange",
  "papaya",
  "passion fruit",
  "peach",
  "pear",
  "pineapple",
  "plum",
  "pomegranate",
  "quince",
  "raspberry",
  "strawberry",
  "watermelon",
  "salad",
  "pizza",
  "pasta",
  "popcorn",
  "lobster",
  "steak",
  "bbq",
  "pudding",
  "hamburger",
  "pie",
  "cake",
  "sausage",
  "tacos",
  "kebab",
  "poutine",
  "seafood",
  "chips",
  "fries",
  "masala",
  "paella",
  "som tam",
  "chicken",
  "toast",
  "marzipan",
  "tofu",
  "ketchup",
  "hummus",
  "chili",
  "maple syrup",
  "parma ham",
  "fajitas",
  "champ",
  "lasagna",
  "poke",
  "chocolate",
  "croissant",
  "arepas",
  "bunny chow",
  "pierogi",
  "donuts",
  "rendang",
  "sushi",
  "ice cream",
  "duck",
  "curry",
  "beef",
  "goat",
  "lamb",
  "turkey",
  "pork",
  "fish",
  "crab",
  "bacon",
  "ham",
  "pepperoni",
  "salami",
  "ribs",
  "noodle",
].sort((a, b) => a.localeCompare(b));

export const LETTERS = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];

export const COLLECTIONS = [
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2021/12/clementine-duck-e584b78.jpg?webp=true&quality=90&resize=408%2C370",
    title: "November recipes",
    query: "broccoli",
    id: "November recipes",
    path: "/collections/November recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2022/05/Airfryer-hero-image-2a442a6.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Air fryer recipes",
    query: "tomato",
    id: "Air fryer recipes",
    path: "/collections/Air fryer recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2022/04/carrot-pilaf-6cf6eba.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Budget healthy recipes",
    query: "zucchini",
    id: "Budget healthy recipes",
    path: "/collections/Budget healthy recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chciken_biryani-a07f546.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Easy family curry recipes",
    query: "curry",
    id: "Easy family curry recipes",
    path: "/collections/Easy family curry recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2022/10/slow-cooker-butter-chicken-931e994.jpg?webp=true&quality=90&resize=620%2C563",
    title: "Budget slow-cooker recipes",
    query: "fish",
    id: "Budget slow-cooker recipes",
    path: "/collections/Budget slow-cooker recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2022/07/Spinach-sweet-potato-lentil-dhal-2d76b5c.jpg?webp=true&quality=90&resize=620%2C563",
    title: "Healthy vegetarian recipes",
    query: "pizza",
    id: "Healthy vegetarian recipes",
    path: "/collections/Healthy vegetarian recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mealprep-pasta-merged_web3_copy-6087bd8.jpg?webp=true&quality=90&resize=500%2C454",
    title: "80 meal prep ideas",
    query: "pudding",
    id: '80 meal prep ideas"',
    path: "/collections/80 meal prep ideas  ",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chicken-chorizo-ragu-773ab7d.jpg?webp=true&quality=90&resize=500%2C454",
    title: "Freezable family recipes",
    query: "chips",
    id: "Freezable family recipes",
    path: "/collections/Freezable family recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2022/04/vegan-mug-cake-cbcc296.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Microwave desserts",
    query: "chicken",
    id: "Microwave desserts",
    path: "/collections/Microwave desserts",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/gfo_1112_cake_so_hr-1-0278f06.jpg?webp=true&quality=90&resize=400%2C363",
    title: "Christmas cake recipes",
    query: "chocolate",
    id: "Christmas cake recipes",
    path: "/collections/Christmas cake recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2022/09/slow-cooker-pork-3c6d196.jpg?webp=true&quality=90&resize=408%2C370",
    title: "No-oven Sunday lunch recipes",
    query: "donuts",
    id: "No-oven Sunday lunch recipes",
    path: "/collections/No-oven Sunday lunch recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/tuscan-sausage-kale-ciabatta-stuffing_1-05fa8a2.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Make-ahead Christmas recipes",
    query: "seafood",
    id: "Make-ahead Christmas recipes",
    path: "/collections/Make-ahead Christmas recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Turkey-cob-salad-copy-28e138f.jpg?webp=true&quality=90&resize=620%2C563",
    title: "Christmas Turkey Recipes",
    query: "turkey",
    id: "Christmas Turkey Recipes",
    path: "/collections/Christmas Turkey Recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/rainbow-prawn-cocktails-e837929.jpg?webp=true&quality=90&resize=500%2C454",
    title: "Quick Nibbles Recipes",
    query: "apricot",
    id: "Quick Nibbles Recipes",
    path: "/collections/Quick Nibbles Recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
  {
    image_url:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/christmas-pudding-ice-cream-31fa57c.jpg?webp=true&quality=90&resize=500%2C454",
    title: "Christmas Pudding Recipes",
    query: "pudding",
    id: "Christmas Pudding Recipes",
    path: "/collections/Christmas Pudding Recipes",
    description:
      "felis bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim sit amet venenatis urna cursus eget nunc scelerisque viverra mauris",
  },
];

export const NUTRITION = [
  {
    label: "Total Fat",
    quantity: "41g",
    percent: "52%",
  },
  {
    label: "Saturated Fat",
    quantity: "21g",
    percent: "105%",
  },
  {
    label: "Cholesterol",
    quantity: "236mg",
    percent: "79%",
  },
  {
    label: "Sodium",
    quantity: "902mg",
    percent: "39%",
  },
  {
    label: "Total Carbohydrate",
    quantity: "1g",
    percent: "0%",
  },
  {
    label: "Dietary Fiber",
    quantity: "0g",
    percent: "1%",
  },
  {
    label: "Total Sugars",
    quantity: "0g",
    percent: "",
  },
  {
    label: "Protein",
    quantity: "52g",
    percent: "",
  },
  {
    label: "Vitamin C",
    quantity: "0mg",
    percent: "1%",
  },
  {
    label: "Calcium",
    quantity: "44mg",
    percent: "3%",
  },
  {
    label: "Iron",
    quantity: "5mg",
    percent: "28%",
  },
  {
    label: "Potassium",
    quantity: "776mg",
    percent: "",
  },
];
