export const SEARCH_QUERIES = [
  "carrot",
  "broccoli",
  "asparagus",
  "cauliflower",
  "corn",
  "cucumber",
  "green pepper",
  "lettuce",
  "mushrooms",
  "onion",
  "potato",
  "pumpkin",
  "red pepper",
  "tomato",
  "beetroot",
  "brussel sprouts",
  "peas",
  "zucchini",
  "radish",
  "sweet potato",
  "artichoke",
  "leek",
  "cabbage",
  "celery",
  "chili",
  "garlic",
  "basil",
  "coriander",
  "parsley",
  "dill",
  "rosemary",
  "oregano",
  "cinnamon",
  "saffron",
  "green bean",
  "bean",
  "chickpea",
  "lentil",
  "apple",
  "apricot",
  "avocado",
  "banana",
  "blackberry",
  "blackcurrant",
  "blueberry",
  "boysenberry",
  "cherry",
  "coconut",
  "fig",
  "grape",
  "grapefruit",
  "kiwi",
  "lemon",
  "lime",
  "lychee",
  "mandarin",
  "mango",
  "melon",
  "nectarine",
  "orange",
  "papaya",
  "passion fruit",
  "peach",
  "pear",
  "pineapple",
  "plum",
  "pomegranate",
  "quince",
  "raspberry",
  "strawberry",
  "watermelon",
  "salad",
  "pizza",
  "pasta",
  "popcorn",
  "lobster",
  "steak",
  "bbq",
  "pudding",
  "hamburger",
  "pie",
  "cake",
  "sausage",
  "tacos",
  "kebab",
  "poutine",
  "seafood",
  "chips",
  "fries",
  "masala",
  "paella",
  "som tam",
  "chicken",
  "toast",
  "marzipan",
  "tofu",
  "ketchup",
  "hummus",
  "chili",
  "maple syrup",
  "parma ham",
  "fajitas",
  "champ",
  "lasagna",
  "poke",
  "chocolate",
  "croissant",
  "arepas",
  "bunny chow",
  "pierogi",
  "donuts",
  "rendang",
  "sushi",
  "ice cream",
  "duck",
  "curry",
  "beef",
  "goat",
  "lamb",
  "turkey",
  "pork",
  "fish",
  "crab",
  "bacon",
  "ham",
  "pepperoni",
  "salami",
  "ribs",
  "noodle",
].sort((a, b) => a.localeCompare(b));

export const LETTERS = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];

export const COLLECTIONS = [
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2021/12/clementine-duck-e584b78.jpg?webp=true&quality=90&resize=408%2C370",
    title: "November recipes",
    query: "broccoli",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2022/05/Airfryer-hero-image-2a442a6.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Air fryer recipes",
    query: "tomato",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2022/04/carrot-pilaf-6cf6eba.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Budget healthy recipes",
    query: "zucchini",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chciken_biryani-a07f546.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Easy family curry recipes",
    query: "curry",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2022/10/slow-cooker-butter-chicken-931e994.jpg?webp=true&quality=90&resize=620%2C563",
    title: "Budget slow-cooker recipes",
    query: "fish",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2022/07/Spinach-sweet-potato-lentil-dhal-2d76b5c.jpg?webp=true&quality=90&resize=620%2C563",
    title: "Healthy vegetarian recipes",
    query: "pizza",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mealprep-pasta-merged_web3_copy-6087bd8.jpg?webp=true&quality=90&resize=500%2C454",
    title: "80 meal prep ideas",
    query: "pudding",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/chicken-chorizo-ragu-773ab7d.jpg?webp=true&quality=90&resize=500%2C454",
    title: "Freezable family recipes",
    query: "chips",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2022/04/vegan-mug-cake-cbcc296.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Microwave desserts",
    query: "chicken",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/gfo_1112_cake_so_hr-1-0278f06.jpg?webp=true&quality=90&resize=400%2C363",
    title: "Christmas cake recipes",
    query: "chocolate",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2022/09/slow-cooker-pork-3c6d196.jpg?webp=true&quality=90&resize=408%2C370",
    title: "No-oven Sunday lunch recipes",
    query: "donuts",
  },
  {
    url: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/tuscan-sausage-kale-ciabatta-stuffing_1-05fa8a2.jpg?webp=true&quality=90&resize=408%2C370",
    title: "Make-ahead Christmas recipes",
    query: "seafood",
  },
];
